# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = ""

default_platform(:ios)

platform :ios do

  lane :tests do |options|
    run_tests(
      project: 'Example/ExampleApp.xcodeproj',
      scheme: options[:scheme],
      cloned_source_packages_path: 'SourcePackagesCache',
      destination: 'platform=iOS Simulator,name=iPhone 13',
      derived_data_path: 'DerivedDataCache',
      skip_package_dependencies_resolution: true,
      skip_build: true
    )
  end

  lane :build do |options|
    xcodebuild(
      project: 'Example/ExampleApp.xcodeproj',
      scheme: options[:scheme],
      destination: 'platform=iOS Simulator,name=iPhone 13',
      xcargs: "-clonedSourcePackagesDirPath SourcePackagesCache -derivedDataPath DerivedDataCache"
    )
  end

end