name: 'run_tests_without_building'
description: 'Executes specific Swift tests using prebuilt artifacts from build_artifacts.yml workflow from main branch'
inputs:
  type:
    description: 'The type of CI step to run'
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'relay.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
          name: main-derivedData
          workflow: build_artifacts.yml
          repo: 'WalletConnect/WalletConnectSwiftV2'
          if_no_artifact_found: warn

    - name: Untar DerivedDataCache
      shell: bash
      run: test -f products.tar && tar xPpf products.tar || echo "No artifacts to untar"

      # Package Unit tests
    - name: Run tests
      if: inputs.type == 'unit-tests'
      shell: bash
      run: make unit_tests

     # Integration tests
    - name: Run integration tests
      if: inputs.type == 'integration-tests'
      shell: bash
      run: make integration_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }}

    # Relay Integration tests
    - name: Run Relay integration tests
      if: inputs.type == 'relay-tests'
      shell: bash
      run: make relay_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }}

    # Smoke tests
    - name: Run smoke tests
      if: inputs.type == 'smoke-tests'
      shell: bash
      run: make smoke_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
          check_name: ${{ inputs.type }} junit report
          report_paths: 'test_results/report.junit'
       
    - name: Zip test artifacts
      if: always()
      shell: bash
      run: test -d "test_results" && zip artifacts.zip -r ./test_results || echo "Nothing to zip"

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.type }} test_results
        path: ./artifacts.zip
        if-no-files-found: warn