name: 'run_tests_without_building'
description: 'Executes specific Swift tests using prebuilt artifacts from build_artifacts.yml workflow from main branch'
inputs:
  type:
    description: 'The type of CI step to run'
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'relay.walletconnect.com'
  notify-endpoint:
    description: 'The endpoint of the notify server e.g. cast.walletconnect.com'
    required: false
    default: 'cast.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true
  slack-webhook-url:
    description: 'Smoke tests slack webhoook url'
    required: false
  gm-dapp-project-id:
    description: 'GM DApp Project ID'
    required: false
  gm-dapp-project-secret:
    description: 'GM DApp Project Secret'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
          name: main-derivedData
          workflow: build_artifacts.yml
          repo: 'WalletConnect/WalletConnectSwiftV2'
          if_no_artifact_found: warn

    - name: Untar DerivedDataCache
      shell: bash
      run: test -f products.tar && tar xPpf products.tar || echo "No artifacts to untar"

    # Package Unit tests
    - name: Run tests
      if: inputs.type == 'unit-tests'
      shell: bash
      run: make unit_tests

     # Integration tests
    - name: Run integration tests
      if: inputs.type == 'integration-tests'
      shell: bash
      run: make integration_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }} CAST_HOST=${{ inputs.notify-endpoint }} GM_DAPP_PROJECT_ID=${{ inputs.gm-dapp-project-id }} GM_DAPP_PROJECT_SECRET=${{ inputs.gm-dapp-project-secret }}

    # Relay Integration tests
    - name: Run Relay integration tests
      if: inputs.type == 'relay-tests'
      shell: bash
      run: make relay_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }} CAST_HOST=${{ inputs.notify-endpoint }}

    # Smoke tests
    - name: Run smoke tests
      if: inputs.type == 'smoke-tests'
      shell: bash
      run: make smoke_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }}

    # Notify tests
    - name: Run notify tests
      if: inputs.type == 'notify-tests'
      shell: bash
      run: make notify_tests RELAY_HOST=${{ inputs.relay-endpoint }} PROJECT_ID=${{ inputs.project-id }} CAST_HOST=${{ inputs.notify-endpoint }} GM_DAPP_PROJECT_ID=${{ inputs.gm-dapp-project-id }} GM_DAPP_PROJECT_SECRET=${{ inputs.gm-dapp-project-secret }}

    # Slack notification for failing smoke and relay tests
    - name: Slack Notification for Failure
      if: failure() && (inputs.type == 'smoke-tests' || inputs.type == 'relay-tests')
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: The smoke tests failed in the CI pipeline. Check the logs for more details.
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
          check_name: ${{ inputs.type }} junit report
          report_paths: 'test_results/report.junit'

    - name: Zip test artifacts
      if: always()
      shell: bash
      run: test -d "test_results" && zip artifacts.zip -r ./test_results || echo "Nothing to zip"

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.type }} test_results
        path: ./artifacts.zip
        if-no-files-found: warn
